// Generated by vibfpga.export; actual implementation evidence is in model.json.
`define VIB_N 1024
`define VIB_FEATURES 16
`define VIB_HIDDEN 16
`define VIB_CLASSES 3
`define VIB_HIDDEN_SHIFT 8
`define VIB_DFT_SHIFT 20
