"""Model/ROM/replay export, with explicit training and provenance metadata."""
import json
from pathlib import Path
import numpy as np
from .fixed import classify, coefficients


def write_hex(path, values, bits):
    mask = (1 << bits) - 1
    digits = (bits + 3) // 4
    Path(path).write_text("".join(f"{int(v) & mask:0{digits}x}\n" for v in np.asarray(values).flat))


def export_model(model, directory):
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    n = int(model["n"])
    hann, cosine, _ = coefficients(n)
    (directory / "model.json").write_text(json.dumps(model, indent=2) + "\n")
    for filename, data, bits in [
        ("bins.hex", model["bins"], 16),
        ("feature_shifts.hex", model["feature_shifts"], 8),
        ("hann.hex", hann, 16), ("hann_quarter.hex", hann[:n // 4], 16),
        ("cos_quarter.hex", cosine[:n // 4], 16),
        ("w1.hex", model["w1"], 8), ("b1.hex", model["b1"], 32),
        ("w2.hex", model["w2"], 8), ("b2.hex", model["b2"], 32),
    ]:
        write_hex(directory / filename, data, bits)
    # Pre-bank weights offline: some synthesis frontends cannot constant-fold
    # an initial block that copies one inferred ROM into separate lane banks.
    # Each bank stores its hidden-neuron rows, then its output-neuron rows.
    w1, w2 = np.asarray(model["w1"]), np.asarray(model["w2"])
    for lanes in (1, 4):
        for bank in range(lanes):
            bank_values = []
            for group in range((w1.shape[0] + lanes - 1) // lanes):
                row = group * lanes + bank
                bank_values.extend(w1[row].tolist() if row < w1.shape[0] else [0] * w1.shape[1])
            for group in range((w2.shape[0] + lanes - 1) // lanes):
                row = group * lanes + bank
                bank_values.extend(w2[row].tolist() if row < w2.shape[0] else [0] * w2.shape[1])
            write_hex(directory / f"weights_l{lanes}_{bank}.hex", bank_values, 8)
    if model.get("feature_mode") == "neighbor3_energy":
        write_hex(directory / "dft_bins.hex",model["dft_bins"],16)
    (directory / "model_config.svh").write_text(
        "// Generated by vibfpga.export; actual implementation evidence is in model.json.\n"
        f"`define VIB_N {n}\n`define VIB_FEATURES {len(model['bins'])}\n"
        f"`define VIB_HIDDEN {len(model['b1'])}\n`define VIB_CLASSES {len(model['b2'])}\n"
        f"`define VIB_HIDDEN_SHIFT {model['hidden_shift']}\n"
        f"`define VIB_BINS_PER_FEATURE {3 if model.get('feature_mode') == 'neighbor3_energy' else 1}\n"
        f"`define VIB_DFT_SHIFT {model['dft_shift']}\n")


def export_vectors(model, frames, metadata, directory, prefix="replay"):
    """Export one signed-16 raw hex and JSON reference per frame, plus JSONL.

    JSON retains every specified intermediate for RTL debugging. This function
    does not communicate with or program any hardware.
    """
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    entries = []
    for index, (frame, meta) in enumerate(zip(frames, metadata)):
        stem = f"{prefix}_{index:03d}"
        expected = classify(np.asarray(frame, dtype=np.int16), model)
        entry = {"frame_id": index, "samples_hex": f"{stem}.hex", "provenance": meta,
                 "expected": {k: v.tolist() if isinstance(v, np.ndarray) else v for k, v in expected.items()}}
        write_hex(directory / f"{stem}.hex", frame, 16)
        (directory / f"{stem}.json").write_text(json.dumps(entry, indent=2) + "\n")
        entries.append(entry)
    (directory / "vectors.jsonl").write_text("".join(json.dumps(entry) + "\n" for entry in entries))
    (directory / "manifest.json").write_text(json.dumps({"schema_version": 1, "n": model["n"],
        "count": len(entries), "physical_board_tested": False,
        "model_training_status": model.get("training_status", "unknown"),
        "vectors": [{k: e[k] for k in ("frame_id", "samples_hex", "provenance")} for e in entries]}, indent=2) + "\n")
    return entries
