#!/usr/bin/env python3
"""Render an evidence-backed animation of simulated RTL outputs; no hardware I/O."""
from datetime import datetime,timezone
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys

ROOT=Path(__file__).resolve().parents[1]
os.environ.setdefault("MPLCONFIGDIR",str(ROOT/"build/matplotlib"))
sys.path.insert(0,str(ROOT/"src"))
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from vibfpga.fixed import classify,frontend
from vibfpga.sensor import parse_sensor_log


def main():
    ffmpeg=shutil.which("ffmpeg")
    if not ffmpeg:raise RuntimeError("Local ffmpeg unavailable; no installation attempted")
    output=ROOT/"artifacts/demo"
    snapshots=output/"source_snapshots"
    snapshots.mkdir(parents=True,exist_ok=True)
    sources=[]
    def read(relative,snapshot):
        path=ROOT/relative
        data=path.read_bytes()
        (snapshots/snapshot).write_bytes(data)
        sources.append({"project_path":relative,"sha256":hashlib.sha256(data).hexdigest(),
                        "snapshot_file":str(Path("source_snapshots")/snapshot)})
        return data
    model_bytes=read("artifacts/model_neighbor/model.json","neighbor_model.json")
    model=json.loads(model_bytes)
    flash=json.loads(read("build/flash_system_neighbor/regression.json","flash_rtl_regression.json"))
    core=json.loads(read("build/core_l4_model_neighbor/regression.json","core_rtl_regression.json"))
    assert flash["passed"] and core["status"]=="passed"
    sha=hashlib.sha256(model_bytes).hexdigest()
    assert flash["model_sha256"]==core["model_sha256"]==sha
    frames,vectors,reference=[],[],[]
    for i in range(2):
        blob=read(f"artifacts/vectors_neighbor/replay_{i:03d}.hex",f"validation_{i}.hex")
        raw=np.array([int(v,16) for v in blob.decode().split()],dtype=np.int64)
        raw[raw>=32768]-=65536
        vector=json.loads(read(f"artifacts/vectors_neighbor/replay_{i:03d}.json",f"validation_{i}.json"))
        expected=classify(raw,model)
        assert vector["provenance"]["split"]=="validation"
        assert expected["logits"].tolist()==flash["log"]["records"][i]["logits"]
        assert expected["class_id"]==flash["log"]["records"][i]["class_id"]
        frames.append(raw);vectors.append(vector);reference.append(expected)
    sensor_report=json.loads(read("build/sensor_system_spectrum/report.json","sensor_rtl_regression.json"))
    assert sensor_report["passed"] and sensor_report["spectrum_golden_match"]
    sensor_bytes=read("build/sensor_system_spectrum/sensor_log.bin","sensor_spi_simulation.bin")
    sensor_meta,sensor_raw,_=parse_sensor_log(sensor_bytes)
    stimulus=json.loads(read("build/sensor_system_spectrum/sensor_stimulus.json","sensor_simulation_stimulus.json"))
    assert stimulus["simulation_only"] is True
    sensor_model=json.loads(read("artifacts/sensor_spectrum/model/model.json","sensor_dsp_profile.json"))
    sen_expected=frontend(np.clip(np.array(stimulus["raw_axis"][-256:],dtype=np.int64),-1024,1023)*32,sensor_model)
    assert sen_expected["powers"].tolist()==sensor_meta["spectrum"]["powers"]
    sensor_power=np.array(sensor_meta["spectrum"]["powers"])
    plt.rcParams.update({"font.family":"DejaVu Sans","font.size":10,"axes.titlesize":12,
        "text.color":"#e9f0fa","axes.labelcolor":"#a9bbd2","xtick.color":"#9db0c9",
        "ytick.color":"#9db0c9","axes.edgecolor":"#2b405e","axes.facecolor":"#111e31",
        "figure.facecolor":"#081321","grid.color":"#29405e","grid.alpha":0.45})
    fig=plt.figure(figsize=(16,9),dpi=90)
    gs=fig.add_gridspec(3,2,left=0.065,right=0.965,bottom=0.115,top=0.80,
                      hspace=0.65,wspace=0.24,width_ratios=[1.38,1],height_ratios=[1.05,1.05,0.95])
    wave=fig.add_subplot(gs[0,0]);bands=fig.add_subplot(gs[1,0]);logits=fig.add_subplot(gs[2,0])
    senwave=fig.add_subplot(gs[0,1]);senbands=fig.add_subplot(gs[1,1]);proof=fig.add_subplot(gs[2,1])
    for ax in (wave,bands,logits,senwave,senbands):
        ax.spines[["top","right"]].set_visible(False)
        ax.grid(axis="y");ax.set_axisbelow(True)
    fig.text(0.065,0.953,"RTL SIMULATION DEMO",fontsize=24,weight="bold")
    fig.text(0.965,0.952,"NO PHYSICAL HARDWARE",ha="right",fontsize=14,weight="bold",color="#ffbf73",
             bbox={"boxstyle":"round,pad=0.45","facecolor":"#392a20","edgecolor":"#9b6b40"})
    fig.text(0.065,0.895,"CWRU validation replay  |  N1024 + 48-bin DSP + INT8 MLP",fontsize=13,color="#52d4db")
    fig.text(0.585,0.895,"ADXL345 SPI / NOR behavioral simulation",fontsize=12,color="#b7a5fb")
    frame_label=fig.text(0.065,0.858,"",fontsize=10,color="#a9bbd2")
    fig.text(0.585,0.858,"SEN1 log generated by the actual sensor RTL",fontsize=10,color="#a9bbd2")
    fig.text(0.065,0.046,"Animation paced for explanation; not real-time acquisition. Validation examples are not new test-set results.",fontsize=10,color="#a9bbd2")
    fig.text(0.065,0.021,"No board footage, physical measurement, field accuracy, or sensor classification is presented.",fontsize=10,color="#ffbf73")
    timer=fig.text(0.965,0.021,"",fontsize=10,ha="right",color="#a9bbd2")
    x=np.arange(1024)/12.0
    wave_line,=wave.plot([],[],color="#52d4db",lw=1.1)
    wave.set_xlim(0,x[-1])
    amplitude=1.2*max(int(np.abs(frame).max()) for frame in frames)
    wave.set_ylim(-amplitude,amplitude)
    wave.set_ylabel("PCM16 input");wave.set_xlabel("Window time (ms)")
    wave.set_title("1  Actual public validation waveform",loc="left",pad=9)
    bandbars=bands.bar(np.arange(16),np.zeros(16),color="#37a9b7",width=.72)
    bands.set_xticks(np.arange(16),[str(k) for k in model["bins"]],fontsize=8)
    bands.set_ylabel("log10(energy + 1)");bands.set_xlabel("DFT center bin  |  energy summed over k-1, k, k+1")
    maxband=max(float(np.log10(r["powers"]+1).max()) for r in reference)
    bands.set_ylim(0,maxband*1.15)
    bands.set_title("2  Sixteen integer neighbor-energy features",loc="left",pad=9)
    class_names=["Inner race","Outer race","Ball"]
    logbars=logits.barh(np.arange(3),[0]*3,color="#344c66",height=.52)
    logits.set_yticks(np.arange(3),class_names);logits.invert_yaxis()
    logits.set_xlim(-5000,3000);logits.axvline(0,color="#6d809b",lw=.8)
    logits.set_xlabel("Signed integer logit  (not probability)")
    logits.set_title("3  RTL scores match the Python integer reference",loc="left",pad=9)
    texts=[logits.text(0,i,"",va="center",fontsize=10) for i in range(3)]
    sx=np.arange(len(sensor_raw))/sensor_meta["odr_hz"]*1000
    senline,=senwave.plot([],[],color="#b7a5fb",lw=1)
    senwave.set_xlim(0,sx[-1]);senwave.set_ylim(-600,600)
    senwave.set_ylabel("Raw x-axis counts");senwave.set_xlabel("Simulated sample time (ms)")
    senwave.set_title("Synthetic sensor stimulus read over SPI",loc="left",pad=9)
    senbar=senbands.bar(np.arange(16),[0]*16,color="#8e7cce",width=.72)
    senbands.set_xticks(np.arange(16),[str(k) for k in sensor_model["bins"]],fontsize=8)
    senbands.set_ylim(0,float(np.log10(sensor_power+1).max())*1.15)
    senbands.set_ylabel("log10(power + 1)");senbands.set_xlabel("N256 DFT bin  |  800 samples/s  |  not PSD per Hz")
    senbands.set_title("Latest 16 powers from the committed SEN1 log",loc="left",pad=9)
    proof.axis("off")
    proof.text(0,0.97,"CHECKED BEFORE RENDERING",fontsize=12,weight="bold",va="top",color="#dbe6f5")
    proof.text(0,0.69,"PASS   3 logits + class: Flash RTL vs integer reference\nPASS   16 sensor powers: SEN1 vs integer reference\nPASS   model hash + input provenance",fontsize=10,va="top",linespacing=1.8,color="#96ddcb")
    state=proof.text(0,.04,"",fontsize=11,color="#ffbf73",va="bottom")
    duration,fps=24,12
    encoders=subprocess.run([ffmpeg,"-hide_banner","-encoders"],capture_output=True,text=True,check=True).stdout
    codec="libx264" if "libx264" in encoders else "mpeg4"
    movie=output/"simulation-demo.mp4"
    command=[ffmpeg,"-hide_banner","-loglevel","error","-y","-f","rawvideo","-pix_fmt","rgba",
        "-s","1440x810","-r",str(fps),"-i","-","-an","-c:v",codec,"-pix_fmt","yuv420p","-movflags","+faststart"]
    command += ["-crf","20","-preset","fast"] if codec=="libx264" else ["-q:v","3"]
    command.append(str(movie))
    with (output/"encoding.log").open("w") as log:
        process=subprocess.Popen(command,stdin=subprocess.PIPE,stderr=log)
        try:
            for index in range(duration*fps):
                t=index/fps
                case=int(t//12);phase=t%12
                fraction=min(1.0,phase/4.0)
                length=max(2,int(1024*fraction));senlength=max(2,int(len(sensor_raw)*fraction))
                wave_line.set_data(x[:length],frames[case][:length])
                senline.set_data(sx[:senlength],sensor_raw[:senlength])
                energy_progress=min(1.,max(0.,(phase-3)/2))
                for bar,value in zip(bandbars,np.log10(reference[case]["powers"]+1)):bar.set_height(value*energy_progress)
                for bar,value in zip(senbar,np.log10(sensor_power+1)):bar.set_height(value*energy_progress)
                show_scores=phase>=6
                for j,(bar,text_artist,value) in enumerate(zip(logbars,texts,reference[case]["logits"])):
                    value=int(value) if show_scores else 0
                    bar.set_width(value);bar.set_color("#52d4db" if j==reference[case]["class_id"] else "#435b76")
                    text_artist.set_text(str(value) if show_scores else "")
                    text_artist.set_position((value+90 if value>=0 else value-90,j))
                    text_artist.set_ha("left" if value>=0 else "right")
                provenance=vectors[case]["provenance"]
                frame_label.set_text(f"Record {provenance['record_id']}  |  validation window {provenance['window_index']}  |  2 HP load  |  example {case+1}/2")
                state.set_text("Reading waveforms" if phase<3 else "Computing integer energy" if phase<6 else
                               f"Matched output: {class_names[reference[case]['class_id']]}")
                timer.set_text(f"{t:04.1f} / {duration}s")
                fig.canvas.draw()
                if index in (9*fps,21*fps):fig.savefig(output/f"frame-{index//fps:02d}s.png",dpi=90)
                process.stdin.write(fig.canvas.buffer_rgba())
            process.stdin.close()
            if process.wait()!=0:raise RuntimeError("ffmpeg failed; see encoding.log")
        except BaseException:
            process.kill();raise
    metadata={"created_utc":datetime.now(timezone.utc).isoformat(),"duration_seconds":duration,"fps":fps,
        "resolution":[1440,810],"codec":codec,"physical_hardware_shown":False,"physical_measurements":False,
        "simulation_only":True,"animation_is_realtime":False,"new_test_set_evaluation":False,
        "validated_before_rendering":["two real validation inputs reproduce actual Flash RTL logits/class",
            "actual sensor RTL SEN1 powers reproduce Python integer frontend","model SHA matches RTL reports"],
        "sources":sources,"script_sha256":hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        "video_sha256":hashlib.sha256(movie.read_bytes()).hexdigest()}
    (output/"metadata.json").write_text(json.dumps(metadata,indent=2)+"\n")
    (output/"README.md").write_text("# RTL simulation demo\n\n24-second evidence-backed animation. No physical hardware is shown or measured.\n\n"
        "Left: two actual CWRU validation windows and their integer model outputs checked against the Flash RTL regression. "
        "Right: synthetic ADXL345 SPI stimuli and powers decoded from a SEN1 log generated by the actual sensor RTL. "
        "The animation is explanatory, not a real-time waveform capture. It does not provide a new held-out test result.\n\n"
        "Source snapshots and SHA256 hashes are retained in source_snapshots/ and metadata.json. "
        "Recreate from the project root with `.venv/bin/python scripts/make_simulation_demo.py`; requires local ffmpeg.\n")
    print(movie)


if __name__=="__main__":main()
